import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.font.FontRenderContext;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.PrintWriter;

/**
 * Offline generator for the bitmap font baked into the core.
 *
 * The emulator cannot depend on AWT (it has to run on Android and translate for
 * iOS), so glyphs are rasterised here once and committed as plain data.
 *
 *   javac -d /tmp/fontgen codegen/FontGen.java
 *   java -cp /tmp/fontgen FontGen > core/src/com/mobicore/core/gfx/FontData.java
 */
public final class FontGen {

    private static final int FIRST = 32;
    private static final int LAST = 126;
    private static final int[] SIZES = {10, 13, 16};
    private static final String[] NAMES = {"SMALL", "MEDIUM", "LARGE"};

    public static void main(String[] args) throws Exception {
        PrintWriter out = new PrintWriter(System.out);
        out.println("package com.mobicore.core.gfx;");
        out.println();
        out.println("/**");
        out.println(" * Bitmap glyph data for the three MIDP font sizes.");
        out.println(" *");
        out.println(" * <p>Generated by {@code codegen/FontGen.java}; do not edit by hand. Each");
        out.println(" * glyph is stored as one bit mask per pixel row, most significant bit");
        out.println(" * leftmost, so a face costs a few kilobytes and needs no platform font");
        out.println(" * engine at runtime.</p>");
        out.println(" */");
        out.println("public final class FontData {");
        out.println();
        out.println("    public static final int FIRST_CHAR = " + FIRST + ";");
        out.println("    public static final int LAST_CHAR = " + LAST + ";");
        out.println();
        out.println("    private FontData() {");
        out.println("    }");
        for (int i = 0; i < SIZES.length; i++) {
            emitFace(out, NAMES[i], SIZES[i]);
        }
        out.println("}");
        out.flush();
    }

    private static void emitFace(PrintWriter out, String name, int size) {
        Font font = new Font("SansSerif", Font.PLAIN, size);
        BufferedImage probe = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        Graphics2D probeG = probe.createGraphics();
        probeG.setFont(font);
        FontRenderContext frc = probeG.getFontRenderContext();
        int ascent = (int) Math.ceil(probeG.getFontMetrics().getAscent());
        int descent = (int) Math.ceil(probeG.getFontMetrics().getDescent());
        probeG.dispose();

        int height = ascent + descent;
        int count = LAST - FIRST + 1;
        int[] advances = new int[count];
        int[][] rows = new int[count][height];
        int maxWidth = 0;

        for (int c = FIRST; c <= LAST; c++) {
            String text = String.valueOf((char) c);
            Rectangle2D bounds = font.getStringBounds(text, frc);
            int advance = (int) Math.round(bounds.getWidth());
            if (advance <= 0) {
                advance = size / 2;
            }
            int cell = Math.max(advance + 2, 1);
            BufferedImage image = new BufferedImage(cell, height, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = image.createGraphics();
            g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_OFF);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF);
            g.setColor(Color.BLACK);
            g.fillRect(0, 0, cell, height);
            g.setFont(font);
            g.setColor(Color.WHITE);
            g.drawString(text, 0, ascent);
            g.dispose();

            int index = c - FIRST;
            advances[index] = advance;
            maxWidth = Math.max(maxWidth, advance);
            for (int y = 0; y < height; y++) {
                int mask = 0;
                for (int x = 0; x < Math.min(cell, 16); x++) {
                    if ((image.getRGB(x, y) & 0xFF) > 110) {
                        mask |= 1 << (15 - x);
                    }
                }
                rows[index][y] = mask;
            }
        }

        out.println();
        out.println("    public static final int " + name + "_HEIGHT = " + height + ";");
        out.println("    public static final int " + name + "_ASCENT = " + ascent + ";");
        out.println("    public static final int " + name + "_MAX_WIDTH = " + maxWidth + ";");
        out.println();
        out.println("    public static final byte[] " + name + "_ADVANCE = {");
        StringBuilder line = new StringBuilder("        ");
        for (int i = 0; i < count; i++) {
            line.append(advances[i]).append(i == count - 1 ? "" : ", ");
            if (line.length() > 92) {
                out.println(line);
                line = new StringBuilder("        ");
            }
        }
        if (line.toString().trim().length() > 0) {
            out.println(line);
        }
        out.println("    };");
        out.println();
        out.println("    /** " + count + " glyphs of " + height + " rows, hex encoded row by row. */");
        out.println("    public static final String " + name + "_BITS =");
        StringBuilder bits = new StringBuilder();
        for (int i = 0; i < count; i++) {
            for (int y = 0; y < height; y++) {
                bits.append(hex4(rows[i][y]));
            }
        }
        for (int i = 0; i < bits.length(); i += 76) {
            String chunk = bits.substring(i, Math.min(bits.length(), i + 76));
            boolean last = i + 76 >= bits.length();
            out.println("            \"" + chunk + "\"" + (last ? ";" : " +"));
        }
    }

    private static String hex4(int value) {
        String hex = Integer.toHexString(value & 0xFFFF).toUpperCase();
        while (hex.length() < 4) {
            hex = "0" + hex;
        }
        return hex;
    }
}
