import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.font.FontRenderContext;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

/**
 * Offline generator for the bitmap fonts.
 *
 * Two very different fonts come out of the same rasteriser:
 *
 *   midp  the three sizes an emulated game sees. These match what a real
 *         handset offered — roughly 13, 16 and 19 pixels tall on a QVGA
 *         screen — and are one bit per pixel, because that is what MIDP
 *         fonts were. Goes into the portable core.
 *
 *   ui    the faces the interface itself draws with. Larger, and two bits of
 *         coverage per pixel so edges are smooth instead of jagged. Desktop
 *         preview only, so it never adds weight to a mobile build.
 *
 *   javac -encoding UTF-8 -d /tmp/fontgen codegen/FontGen.java
 *   java -Djava.awt.headless=true -cp /tmp/fontgen FontGen midp \
 *       > core/src/com/mobicore/core/gfx/FontData.java
 *   java -Djava.awt.headless=true -cp /tmp/fontgen FontGen ui \
 *       > tools/src/com/mobicore/tools/ui/UiFontData.java
 *
 * The character set covers ASCII plus the whole of Vietnamese, including every
 * tone mark combination. Without it, interface text and Vietnamese game text
 * would render as question marks.
 */
public final class FontGen {

    private static final String[] MIDP_NAMES = {"SMALL", "MEDIUM", "LARGE"};
    private static final int[] MIDP_SIZES = {10, 12, 15};

    private static final String[] UI_NAMES = {"SMALL", "BODY", "LARGE", "TITLE"};
    private static final int[] UI_SIZES = {14, 17, 21, 28};

    /** DejaVu Sans is legible at small sizes and covers Vietnamese completely. */
    private static final String[] FAMILIES = {"DejaVu Sans", "Liberation Sans", "SansSerif"};

    private static boolean antiAliased;

    public static void main(String[] args) throws Exception {
        String mode = args.length > 0 ? args[0] : "midp";
        antiAliased = "ui".equals(mode);
        String[] names = antiAliased ? UI_NAMES : MIDP_NAMES;
        int[] sizes = antiAliased ? UI_SIZES : MIDP_SIZES;

        String family = pickFamily();
        char[] charset = buildCharset(family);

        PrintWriter out = new PrintWriter(new java.io.OutputStreamWriter(System.out, "UTF-8"));
        header(out, family, charset);
        for (int i = 0; i < names.length; i++) {
            emitFace(out, family, names[i], sizes[i], charset);
        }
        out.println("}");
        out.flush();
    }

    private static String pickFamily() {
        for (String candidate : FAMILIES) {
            Font font = new Font(candidate, Font.PLAIN, 16);
            if (font.getFamily().equals(candidate) && font.canDisplay('ế')) {
                return candidate;
            }
        }
        return "SansSerif";
    }

    /** ASCII, then Vietnamese, then the symbols the interface draws as text. */
    private static char[] buildCharset(String family) {
        Font probe = new Font(family, Font.PLAIN, 16);
        List<Character> chars = new ArrayList<Character>();
        for (char c = 32; c <= 126; c++) {
            chars.add(Character.valueOf(c));
        }
        String latin1 = "ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝàáâãèéêìíòóôõùúýÄÖÜäöüÑñÇç";
        String extended = "ĂăĐđĨĩŨũƠơƯư";
        for (int i = 0; i < latin1.length(); i++) {
            chars.add(Character.valueOf(latin1.charAt(i)));
        }
        for (int i = 0; i < extended.length(); i++) {
            chars.add(Character.valueOf(extended.charAt(i)));
        }
        for (char c = 0x1EA0; c <= 0x1EF9; c++) {
            chars.add(Character.valueOf(c));
        }
        String symbols = "·…–—×°«»‹›“”‘’€₫←→↑↓▲▼◀▶●○✓✕★☆♪";
        for (int i = 0; i < symbols.length(); i++) {
            chars.add(Character.valueOf(symbols.charAt(i)));
        }

        List<Character> usable = new ArrayList<Character>();
        for (Character c : chars) {
            if (!usable.contains(c) && probe.canDisplay(c.charValue())) {
                usable.add(c);
            }
        }
        char[] result = new char[usable.size()];
        for (int i = 0; i < result.length; i++) {
            result[i] = usable.get(i).charValue();
        }
        return result;
    }

    private static void header(PrintWriter out, String family, char[] charset) {
        String className = antiAliased ? "UiFontData" : "FontData";
        out.println(antiAliased
                ? "package com.mobicore.tools.ui;"
                : "package com.mobicore.core.gfx;");
        out.println();
        out.println("/**");
        if (antiAliased) {
            out.println(" * Anti-aliased glyph data for the interface faces.");
            out.println(" *");
            out.println(" * <p>Generated by {@code codegen/FontGen.java ui} from " + family + ";");
            out.println(" * do not edit by hand. Two bits of coverage per pixel give four levels");
            out.println(" * of opacity, which is enough to take the jagged edges off text without");
            out.println(" * quadrupling the data.</p>");
        } else {
            out.println(" * Bitmap glyph data for the three MIDP font sizes.");
            out.println(" *");
            out.println(" * <p>Generated by {@code codegen/FontGen.java midp} from " + family + ";");
            out.println(" * do not edit by hand. One bit per pixel and sized to match what a real");
            out.println(" * handset offered, because that is what a MIDlet expects when it lays");
            out.println(" * out a screen around {@code Font.getHeight()}.</p>");
        }
        out.println(" *");
        out.println(" * <p>The character set covers ASCII and the whole of Vietnamese, including");
        out.println(" * every tone mark combination, so interface text and game text both render");
        out.println(" * correctly rather than as question marks.</p>");
        out.println(" */");
        out.println("public final class " + className + " {");
        out.println();
        out.println("    private " + className + "() {");
        out.println("    }");
        out.println();
        out.println("    /** Rejoins the chunked row data at class initialisation. */");
        out.println("    private static String join(String[] parts) {");
        out.println("        StringBuilder out = new StringBuilder();");
        out.println("        for (String part : parts) {");
        out.println("            out.append(part);");
        out.println("        }");
        out.println("        return out.toString();");
        out.println("    }");
        out.println();
        out.println("    /** Every supported character, in glyph index order. */");
        out.println("    public static final String CHARSET =");
        emitEscapedString(out, charset);
    }

    private static void emitEscapedString(PrintWriter out, char[] charset) {
        StringBuilder line = new StringBuilder("            \"");
        for (int i = 0; i < charset.length; i++) {
            line.append(escape(charset[i]));
            if (line.length() > 96) {
                out.println(line.append("\" +").toString());
                line = new StringBuilder("            \"");
            }
        }
        out.println(line.append("\";").toString());
    }

    private static String escape(char c) {
        if (c == '"') {
            return "\\\"";
        }
        if (c == '\\') {
            return "\\\\";
        }
        if (c >= 32 && c < 127) {
            return String.valueOf(c);
        }
        String hex = Integer.toHexString(c).toUpperCase();
        while (hex.length() < 4) {
            hex = "0" + hex;
        }
        return "\\u" + hex;
    }

    private static void emitFace(PrintWriter out, String family, String name, int size,
                                 char[] charset) {
        Font font = new Font(family, Font.PLAIN, size);
        BufferedImage probe = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        Graphics2D probeG = probe.createGraphics();
        probeG.setFont(font);
        FontRenderContext frc = probeG.getFontRenderContext();
        probeG.dispose();

        // Rasterise into a cell with generous headroom and then measure where
        // the ink actually lands. Font metrics understate the ascent for
        // Vietnamese: Ẵ and Ẫ stack a tilde on top of an already accented
        // capital, and trusting getMaxAscent clips the top mark clean off.
        int baseline = Math.round(size * 1.9f);
        int cellHeight = Math.round(size * 3.0f);
        int count = charset.length;
        int[] advances = new int[count];
        int[][] coverage = new int[count][];
        int[] cellWidths = new int[count];
        int inkTop = cellHeight;
        int inkBottom = -1;
        int maxWidth = 0;

        for (int index = 0; index < count; index++) {
            String text = String.valueOf(charset[index]);
            Rectangle2D bounds = font.getStringBounds(text, frc);
            int advance = (int) Math.round(bounds.getWidth());
            if (advance <= 0) {
                advance = size / 2;
            }
            int cell = Math.min(32, Math.max(advance + 6, 1));
            BufferedImage image = new BufferedImage(cell, cellHeight, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = image.createGraphics();
            g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                    RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS,
                    RenderingHints.VALUE_FRACTIONALMETRICS_OFF);
            g.setColor(Color.BLACK);
            g.fillRect(0, 0, cell, cellHeight);
            g.setFont(font);
            g.setColor(Color.WHITE);
            g.drawString(text, 0, baseline);
            g.dispose();

            advances[index] = advance;
            cellWidths[index] = cell;
            int[] pixels = new int[cellHeight * cell];
            for (int y = 0; y < cellHeight; y++) {
                boolean inked = false;
                for (int x = 0; x < cell; x++) {
                    int grey = image.getRGB(x, y) & 0xFF;
                    int value = antiAliased ? (grey * 3 + 127) / 255 : (grey >= 96 ? 1 : 0);
                    pixels[y * cell + x] = value;
                    if (value != 0) {
                        inked = true;
                        maxWidth = Math.max(maxWidth, x + 1);
                    }
                }
                if (inked) {
                    inkTop = Math.min(inkTop, y);
                    inkBottom = Math.max(inkBottom, y);
                }
            }
            coverage[index] = pixels;
        }

        if (inkBottom < 0) {
            throw new IllegalStateException("The face rendered nothing at all");
        }
        int ascent = baseline - inkTop;
        int height = inkBottom - inkTop + 1;
        // Each stored int carries 32 pixels at one bit, or 16 at two bits.
        int pixelsPerWord = antiAliased ? 16 : 32;
        int wordsPerRow = (maxWidth + pixelsPerWord - 1) / pixelsPerWord;
        if (wordsPerRow < 1) {
            wordsPerRow = 1;
        }

        // Most glyphs leave the top and bottom of the cell empty, so only the
        // rows that actually carry ink are stored. That roughly halves the data
        // without costing anything at draw time.
        int[] firstRow = new int[count];
        int[] rowCount = new int[count];
        StringBuilder bits = new StringBuilder();
        for (int i = 0; i < count; i++) {
            int cell = cellWidths[i];
            int top = cellHeight;
            int bottom = -1;
            for (int y = 0; y < cellHeight; y++) {
                for (int x = 0; x < cell; x++) {
                    if (coverage[i][y * cell + x] != 0) {
                        if (y < top) {
                            top = y;
                        }
                        bottom = y;
                        break;
                    }
                }
            }
            if (bottom < 0) {
                firstRow[i] = 0;
                rowCount[i] = 0;
                continue;
            }
            firstRow[i] = top - inkTop;
            rowCount[i] = bottom - top + 1;
            for (int y = top; y <= bottom; y++) {
                for (int word = 0; word < wordsPerRow; word++) {
                    int packed = 0;
                    for (int slot = 0; slot < pixelsPerWord; slot++) {
                        int x = word * pixelsPerWord + slot;
                        int value = x < cell ? coverage[i][y * cell + x] : 0;
                        if (antiAliased) {
                            packed |= (value & 3) << (30 - slot * 2);
                        } else {
                            packed |= (value & 1) << (31 - slot);
                        }
                    }
                    bits.append(hex(packed));
                }
            }
        }

        out.println();
        out.println("    public static final int " + name + "_HEIGHT = " + height + ";");
        out.println("    public static final int " + name + "_ASCENT = " + ascent + ";");
        out.println("    public static final int " + name + "_MAX_WIDTH = " + maxWidth + ";");
        out.println("    /** 32-bit words per pixel row. */");
        out.println("    public static final int " + name + "_WORDS = " + wordsPerRow + ";");
        emitByteArray(out, name + "_ADVANCE", advances, "Advance width of each glyph.");
        emitByteArray(out, name + "_TOP", firstRow, "First row of each glyph that carries ink.");
        emitByteArray(out, name + "_ROWS", rowCount, "Number of stored rows per glyph.");

        // Emitted in chunks and joined at run time: a single string constant is
        // limited to 65535 bytes in a class file, which the larger faces exceed.
        out.println();
        out.println("    /** " + count + " glyphs, trimmed to their inked rows. */");
        out.println("    private static final String[] " + name + "_PARTS = {");
        for (int i = 0; i < bits.length(); i += 88) {
            String chunk = bits.substring(i, Math.min(bits.length(), i + 88));
            out.println("        \"" + chunk + "\",");
        }
        out.println("    };");
        out.println();
        out.println("    public static final String " + name + "_BITS = join(" + name + "_PARTS);");
    }

    private static void emitByteArray(PrintWriter out, String name, int[] values, String doc) {
        out.println();
        out.println("    /** " + doc + " */");
        out.println("    public static final byte[] " + name + " = {");
        StringBuilder line = new StringBuilder("        ");
        for (int i = 0; i < values.length; i++) {
            line.append(values[i]).append(i == values.length - 1 ? "" : ", ");
            if (line.length() > 92) {
                out.println(line);
                line = new StringBuilder("        ");
            }
        }
        if (line.toString().trim().length() > 0) {
            out.println(line);
        }
        out.println("    };");
    }

    private static String hex(int value) {
        String hex = Integer.toHexString(value);
        while (hex.length() < 8) {
            hex = "0" + hex;
        }
        return hex.toUpperCase();
    }
}
