import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.font.FontRenderContext;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

/**
 * Offline generator for the bitmap font baked into the core.
 *
 * The emulator cannot depend on AWT (it has to run on Android and translate for
 * iOS), so glyphs are rasterised here once and committed as plain data.
 *
 *   javac -encoding UTF-8 -d /tmp/fontgen codegen/FontGen.java
 *   java -Djava.awt.headless=true -cp /tmp/fontgen FontGen \
 *       > core/src/com/mobicore/core/gfx/FontData.java
 *
 * The character set covers ASCII plus the whole of Vietnamese: the base
 * letters, the seven extra letters (ă â đ ê ô ơ ư) and every tone mark
 * combination in Latin Extended Additional. Without those, the interface and
 * any Vietnamese game text would render as question marks.
 */
public final class FontGen {

    /** Faces: the three MIDP sizes plus one the interface uses for headings. */
    private static final String[] NAMES = {"SMALL", "MEDIUM", "LARGE", "TITLE"};
    private static final int[] SIZES = {13, 16, 20, 28};

    /** DejaVu Sans is legible at small sizes and covers Vietnamese completely. */
    private static final String[] FAMILIES = {"DejaVu Sans", "Liberation Sans", "SansSerif"};

    public static void main(String[] args) throws Exception {
        String family = pickFamily();
        char[] charset = buildCharset(family);

        PrintWriter out = new PrintWriter(new java.io.OutputStreamWriter(System.out, "UTF-8"));
        header(out, family, charset);
        for (int i = 0; i < NAMES.length; i++) {
            emitFace(out, family, NAMES[i], SIZES[i], charset);
        }
        out.println("}");
        out.flush();
    }

    private static String pickFamily() {
        for (String candidate : FAMILIES) {
            Font font = new Font(candidate, Font.PLAIN, 16);
            if (font.getFamily().equals(candidate) && font.canDisplay('ế')) {
                return candidate;
            }
        }
        return "SansSerif";
    }

    /** ASCII, then Vietnamese, then the handful of symbols the interface uses. */
    private static char[] buildCharset(String family) {
        Font probe = new Font(family, Font.PLAIN, 16);
        List<Character> chars = new ArrayList<Character>();
        for (char c = 32; c <= 126; c++) {
            chars.add(Character.valueOf(c));
        }
        // Vietnamese base letters carrying tone marks in Latin-1.
        String latin1 = "ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝàáâãèéêìíòóôõùúýÄÖÜäöüÑñÇç";
        // The seven letters Vietnamese adds to the Latin alphabet.
        String extended = "ĂăĐđĨĩŨũƠơƯư";
        for (int i = 0; i < latin1.length(); i++) {
            chars.add(Character.valueOf(latin1.charAt(i)));
        }
        for (int i = 0; i < extended.length(); i++) {
            chars.add(Character.valueOf(extended.charAt(i)));
        }
        // Latin Extended Additional: every remaining tone combination.
        for (char c = 0x1EA0; c <= 0x1EF9; c++) {
            chars.add(Character.valueOf(c));
        }
        // Arrows and marks the interface draws as text rather than as shapes.
        String symbols = "·…–—×°«»‹›“”‘’€₫←→↑↓▲▼◀▶●○✓✕★☆♪";
        for (int i = 0; i < symbols.length(); i++) {
            chars.add(Character.valueOf(symbols.charAt(i)));
        }

        List<Character> usable = new ArrayList<Character>();
        for (Character c : chars) {
            if (!usable.contains(c) && probe.canDisplay(c.charValue())) {
                usable.add(c);
            }
        }
        char[] result = new char[usable.size()];
        for (int i = 0; i < result.length; i++) {
            result[i] = usable.get(i).charValue();
        }
        return result;
    }

    private static void header(PrintWriter out, String family, char[] charset) {
        out.println("package com.mobicore.core.gfx;");
        out.println();
        out.println("/**");
        out.println(" * Bitmap glyph data for the four font faces.");
        out.println(" *");
        out.println(" * <p>Generated by {@code codegen/FontGen.java} from " + family + "; do not");
        out.println(" * edit by hand. The character set covers ASCII and the whole of Vietnamese,");
        out.println(" * including every tone mark combination, so interface text and game text");
        out.println(" * both render correctly rather than as question marks.</p>");
        out.println(" *");
        out.println(" * <p>Each glyph is one bit mask per pixel row, most significant bit");
        out.println(" * leftmost. Rows are hex encoded; a face whose widest glyph fits in 16");
        out.println(" * pixels uses four hex digits per row instead of eight, which halves the");
        out.println(" * data for the smaller faces.</p>");
        out.println(" */");
        out.println("public final class FontData {");
        out.println();
        out.println("    private FontData() {");
        out.println("    }");
        out.println();
        out.println("    /** Rejoins the chunked row data at class initialisation. */");
        out.println("    private static String join(String[] parts) {");
        out.println("        StringBuilder out = new StringBuilder();");
        out.println("        for (String part : parts) {");
        out.println("            out.append(part);");
        out.println("        }");
        out.println("        return out.toString();");
        out.println("    }");
        out.println();
        out.println("    /** Every supported character, in glyph index order. */");
        out.println("    public static final String CHARSET =");
        emitEscapedString(out, charset);
    }

    private static void emitEscapedString(PrintWriter out, char[] charset) {
        StringBuilder line = new StringBuilder("            \"");
        for (int i = 0; i < charset.length; i++) {
            line.append(escape(charset[i]));
            if (line.length() > 96) {
                out.println(line.append("\" +").toString());
                line = new StringBuilder("            \"");
            }
        }
        out.println(line.append("\";").toString());
    }

    private static String escape(char c) {
        if (c == '"') {
            return "\\\"";
        }
        if (c == '\\') {
            return "\\\\";
        }
        if (c >= 32 && c < 127) {
            return String.valueOf(c);
        }
        String hex = Integer.toHexString(c).toUpperCase();
        while (hex.length() < 4) {
            hex = "0" + hex;
        }
        return "\\u" + hex;
    }

    private static void emitFace(PrintWriter out, String family, String name, int size,
                                 char[] charset) {
        Font font = new Font(family, Font.PLAIN, size);
        BufferedImage probe = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        Graphics2D probeG = probe.createGraphics();
        probeG.setFont(font);
        FontRenderContext frc = probeG.getFontRenderContext();
        probeG.dispose();

        // Rasterise into a cell with generous headroom and then measure where
        // the ink actually lands. Font metrics understate the ascent for
        // Vietnamese: Ẵ and Ẫ stack a tilde on top of an already accented
        // capital, and trusting getMaxAscent clips the top mark clean off.
        int baseline = Math.round(size * 1.9f);
        int cellHeight = Math.round(size * 3.0f);
        int count = charset.length;
        int[] advances = new int[count];
        int[][] raw = new int[count][cellHeight];
        int inkTop = cellHeight;
        int inkBottom = -1;
        int maxWidth = 0;

        for (int index = 0; index < count; index++) {
            String text = String.valueOf(charset[index]);
            Rectangle2D bounds = font.getStringBounds(text, frc);
            int advance = (int) Math.round(bounds.getWidth());
            if (advance <= 0) {
                advance = size / 2;
            }
            int cell = Math.min(32, Math.max(advance + 6, 1));
            BufferedImage image = new BufferedImage(cell, cellHeight, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = image.createGraphics();
            // Antialiasing on, then thresholded: this gives fuller, better
            // shaped stems than hinting-off rendering, which matters for the
            // dense diacritics Vietnamese stacks above its vowels.
            g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                    RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS,
                    RenderingHints.VALUE_FRACTIONALMETRICS_OFF);
            g.setColor(Color.BLACK);
            g.fillRect(0, 0, cell, cellHeight);
            g.setFont(font);
            g.setColor(Color.WHITE);
            g.drawString(text, 0, baseline);
            g.dispose();

            advances[index] = advance;
            for (int y = 0; y < cellHeight; y++) {
                int mask = 0;
                for (int x = 0; x < cell; x++) {
                    if ((image.getRGB(x, y) & 0xFF) >= 96) {
                        mask |= 1 << (31 - x);
                        maxWidth = Math.max(maxWidth, x + 1);
                    }
                }
                raw[index][y] = mask;
                if (mask != 0) {
                    inkTop = Math.min(inkTop, y);
                    inkBottom = Math.max(inkBottom, y);
                }
            }
        }

        if (inkBottom < 0) {
            throw new IllegalStateException("The face rendered nothing at all");
        }
        int ascent = baseline - inkTop;
        int height = inkBottom - inkTop + 1;
        int hexDigits = maxWidth <= 16 ? 4 : 8;

        // Most glyphs leave the top and bottom of the cell empty, so only the
        // rows that actually carry ink are stored. That roughly halves the data
        // without costing anything at draw time.
        int[] firstRow = new int[count];
        int[] rowCount = new int[count];
        StringBuilder bits = new StringBuilder();
        for (int i = 0; i < count; i++) {
            int top = cellHeight;
            int bottom = -1;
            for (int y = 0; y < cellHeight; y++) {
                if (raw[i][y] != 0) {
                    if (y < top) {
                        top = y;
                    }
                    bottom = y;
                }
            }
            if (bottom < 0) {
                firstRow[i] = 0;
                rowCount[i] = 0;
                continue;
            }
            firstRow[i] = top - inkTop;
            rowCount[i] = bottom - top + 1;
            for (int y = top; y <= bottom; y++) {
                int mask = raw[i][y];
                bits.append(hex(hexDigits == 4 ? mask >>> 16 : mask, hexDigits));
            }
        }

        out.println();
        out.println("    public static final int " + name + "_HEIGHT = " + height + ";");
        out.println("    public static final int " + name + "_ASCENT = " + ascent + ";");
        out.println("    public static final int " + name + "_MAX_WIDTH = " + maxWidth + ";");
        out.println("    /** Hex digits per row: four when every glyph fits in 16 pixels. */");
        out.println("    public static final int " + name + "_HEX = " + hexDigits + ";");
        emitByteArray(out, name + "_ADVANCE", advances, "Advance width of each glyph.");
        emitByteArray(out, name + "_TOP", firstRow, "First row of each glyph that carries ink.");
        emitByteArray(out, name + "_ROWS", rowCount, "Number of stored rows per glyph.");

        // Emitted in chunks and joined at run time: a single string constant is
        // limited to 65535 bytes in a class file, which the larger faces exceed.
        out.println();
        out.println("    /** " + count + " glyphs, trimmed to their inked rows. */");
        out.println("    private static final String[] " + name + "_PARTS = {");
        for (int i = 0; i < bits.length(); i += 88) {
            String chunk = bits.substring(i, Math.min(bits.length(), i + 88));
            out.println("        \"" + chunk + "\",");
        }
        out.println("    };");
        out.println();
        out.println("    public static final String " + name + "_BITS = join(" + name + "_PARTS);");
    }

    private static void emitByteArray(PrintWriter out, String name, int[] values, String doc) {
        out.println();
        out.println("    /** " + doc + " */");
        out.println("    public static final byte[] " + name + " = {");
        StringBuilder line = new StringBuilder("        ");
        for (int i = 0; i < values.length; i++) {
            line.append(values[i]).append(i == values.length - 1 ? "" : ", ");
            if (line.length() > 92) {
                out.println(line);
                line = new StringBuilder("        ");
            }
        }
        if (line.toString().trim().length() > 0) {
            out.println(line);
        }
        out.println("    };");
    }

    private static String hex(int value, int digits) {
        String hex = Integer.toHexString(value);
        if (hex.length() > digits) {
            hex = hex.substring(hex.length() - digits);
        }
        while (hex.length() < digits) {
            hex = "0" + hex;
        }
        return hex.toUpperCase();
    }
}
